get http://localhost:3000/user 
x-send : abc
###

POST http://localhost:3000/user 
Content-Type: application/json 


{
   "email" : "abc@2022",
   "nom": "abc",
   "role":"ADMIN"
}

###
DELETE http://localhost:3000/user/1 
x-send : 1
###