get http://localhost:3000/user 
x-send : abc
###

POST http://localhost:3000/user 
Content-Type: application/json 
{
  
   "nom" : "user1",
   "password":"password"
}

###
DELETE http://localhost:3000/user/1 
x-send : 1
###